# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-05 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tracker', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reclamacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_apertura', models.DateTimeField(auto_now_add=True)),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=14)),
                ('tipo_reclamacion', models.CharField(choices=[('1-', 'No pasa el camion'), ('2-', 'Varios dias sin pasar'), ('3-', 'No pasa por la calle'), ('4-', 'Piden dinero'), ('5-', 'Escombros'), ('6-', 'Poda'), ('7-', 'Camion no pasa el dia de su frecuencia'), ('8-', 'Deficiencia servicio'), ('9-', 'Camion pasa muy rapido'), ('10-', 'No se detienen')], max_length=30)),
                ('observaciones', models.CharField(max_length=300)),
                ('fecha_cierre', models.DateTimeField()),
                ('status', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('nombre', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('telefono', models.CharField(max_length=14)),
                ('telefono_2', models.CharField(max_length=14)),
                ('circunscripcion', models.IntegerField()),
                ('compactadores', models.IntegerField()),
                ('camioncitos', models.IntegerField()),
                ('sectores', models.ManyToManyField(to='tracker.Sectores')),
            ],
        ),
    ]
