# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-05 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reclamacion',
            name='tipo_reclamacion',
            field=models.CharField(choices=[('No pasa el camion', '1-No pasa el camion'), ('Varios dias sin pasar', '2-Varios dias sin pasar'), ('No pasa por la calle', '3-No pasa por la calle'), ('Piden dinero', '4-Piden dinero'), ('Escombros', '5-Escombros'), ('Poda', '6-Poda'), ('Camion no pasa el dia de su frecuencia', '7-Camion no pasa el dia de su frecuencia'), ('Deficiencia servicio', '8-Deficiencia servicio'), ('Camion pasa muy rapido', '9-Camion pasa muy rapido'), ('No se detienen', '10-No se detienen')], max_length=30),
        ),
    ]
