# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-05 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamaciones', '0002_auto_20170105_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reclamacion',
            name='observaciones',
            field=models.TextField(max_length=300),
        ),
    ]
