# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-06 00:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '__first__'),
        ('reclamaciones', '0003_auto_20170105_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='reclamacion',
            name='sector',
            field=models.ManyToManyField(to='tracker.Sectores'),
        ),
    ]
