# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-06 01:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '__first__'),
        ('reclamaciones', '0004_reclamacion_sector'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reclamacion',
            name='sector',
        ),
        migrations.AddField(
            model_name='reclamacion',
            name='sector',
            field=models.ForeignKey(default='S/N', on_delete=django.db.models.deletion.CASCADE, to='tracker.Sectores'),
        ),
    ]
