# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-06 01:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamaciones', '0005_auto_20170106_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reclamacion',
            name='fecha_apertura',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='reclamacion',
            name='fecha_cierre',
            field=models.DateField(),
        ),
    ]
