# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-07 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamaciones', '0008_auto_20170106_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reclamacion',
            name='fecha_cierre',
            field=models.DateField(blank=True, null=True),
        ),
    ]
