# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-30 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_auto_20160929_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camiones',
            fields=[
                ('ficha', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('tipo_camion', models.CharField(max_length=20)),
                ('capacidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Compania',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('camiones', models.ManyToManyField(to='tracker.Camiones')),
            ],
        ),
    ]
