# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-30 14:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_camiones_compania'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opeduquesa',
            name='ficha_camion',
            field=models.ForeignKey(max_length=15, on_delete=django.db.models.deletion.CASCADE, to='tracker.Camiones'),
        ),
    ]
