# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-30 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_auto_20160930_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camiones',
            name='ficha',
            field=models.CharField(default=0, max_length=20, primary_key=True, serialize=False),
        ),
    ]
