# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-30 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_auto_20160930_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camiones',
            name='ficha',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
