# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-30 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_auto_20160930_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compania',
            name='camiones',
            field=models.ManyToManyField(null=True, to='tracker.Camiones'),
        ),
    ]
